'use client';
import {useMemo,useState} from 'react';
import {boroughs,type Borough} from '../lib/rats';
import {type RatData,type Sighting} from '../lib/ratconomy';
const colors:Record<Borough,string>={Allston:'#227b55','Back Bay':'#1769a8','Beacon Hill':'#8c67b4',Dorchester:'#c97b35','East Boston':'#bd5670','Jamaica Plain':'#119a98',Roxbury:'#795548','South Boston':'#6b62ad'};
const bounds={west:-71.20,east:-70.97,north:42.42,south:42.22};
function position(p:Sighting){return{x:30+(p.longitude-bounds.west)/(bounds.east-bounds.west)*640,y:25+(bounds.north-p.latitude)/(bounds.north-bounds.south)*470}}
export default function RatMap({data,onBorough}:{data:RatData;onBorough?:(b:Borough)=>void}){
const[filter,setFilter]=useState<Borough|'All'>('All');const[picked,setPicked]=useState<number|null>(null);
const visible=useMemo(()=>data.points.map((p,i)=>({...p,index:i})).filter(p=>filter==='All'||p.borough===filter),[data.points,filter]);const point=picked===null?null:data.points[picked];
return <div className="map-section"><div className="map-controls"><strong>🗺️ Boston rodent report explorer</strong><select aria-label="Filter map by neighborhood" value={filter} onChange={e=>{setFilter(e.target.value as Borough|'All');setPicked(null)}}><option>All</option>{boroughs.map(b=><option key={b}>{b}</option>)}</select></div><div className="map-layout"><div className="map-canvas"><svg viewBox="0 0 700 520" role="img" aria-label={`${visible.length} ${data.source==='live'?'reported Boston rodent locations':'illustrative Boston points'} positioned from latitude and longitude`}>
<defs><pattern id="roads" patternUnits="userSpaceOnUse" width="33" height="33"><path d="M33 0H0V33" stroke="#d5e7e5" strokeWidth="1" fill="none"/></pattern></defs><rect width="700" height="520" fill="#eff7f6"/><rect width="700" height="520" fill="url(#roads)"/>
<path d="M440 0C370 80 475 175 400 235S400 315 505 375 575 450 590 520L700 520V0Z" fill="#d9eff4"/><path d="M200 0L375 0 365 240 455 290 360 520 0 520 0 0Z" fill="#e1eadd" opacity=".62"/>
<g fill="#617e77" fontSize="14" fontWeight="700" opacity=".76"><text x="165" y="168">ALLSTON</text><text x="295" y="235">BACK BAY</text><text x="365" y="186">BEACON HILL</text><text x="255" y="320">ROXBURY</text><text x="170" y="392">JAMAICA PLAIN</text><text x="330" y="455">DORCHESTER</text><text x="492" y="207">EAST BOSTON</text><text x="470" y="350">SOUTH BOSTON</text></g>
{visible.map(p=>{const{x,y}=position(p);return <circle key={p.index} cx={x} cy={y} r={picked===p.index?9:4.5} stroke="#fff" strokeWidth="1.3" fill={colors[p.borough]} opacity={picked===p.index?1:.82} className="map-point" tabIndex={0} role="button" aria-label={`${p.borough} report ${p.date}`} onClick={()=>setPicked(p.index)} onKeyDown={e=>{if(e.key==='Enter')setPicked(p.index)}}><title>{`${p.borough} · ${p.date}`}</title></circle>})}<text x="14" y="508" fontSize="10" fill="#657f7c">Schematic Boston backdrop · plotted GPS points · not a navigation map</text></svg></div><div className="map-details"><div className="map-stat">{visible.length} <span>plotted reports</span></div><p>{data.source==='live'?'Up to 450 recent geocoded reports in the eight displayed neighborhood groups.':'ILLUSTRATIVE SAMPLE DOTS — not verified reports.'}</p>{point?<div className="point-card"><strong>📍 {point.borough}</strong><span>{point.date||'Date unavailable'}</span><span>ZIP: {point.zip||'Not available'}</span><button onClick={()=>onBorough?.(point.borough)}>Meet local professionals →</button></div>:<p>Click a dot to inspect its report date.</p>}{boroughs.map(b=><button className="legend-row" key={b} onClick={()=>{setFilter(b);setPicked(null)}}><i style={{background:colors[b]}}/>{b}<span>{data.counts[b].toLocaleString()} reports</span></button>)}<small>Groups are selected neighborhoods, not a complete Boston breakdown; some addresses use nearest-center approximations. Reports are not individual animals.</small></div></div></div>
}
