'use client';
import {useEffect,useState} from 'react';
import {boroughs,type Borough} from '../lib/rats';
import {cloudAdd,cloudProfiles,cloudReady,auth,freshSession,loadLocal,loadSession,saveLocal,saveSession,type CustomRat,type Session} from '../lib/account';
export default function RatStudio({onNew}:{onNew?:(profile:CustomRat)=>void}){
 const [name,setName]=useState('');const[borough,setBorough]=useState<Borough>('Allston');const[neighborhood,setNeighborhood]=useState('Allston');const[generated,setGenerated]=useState<CustomRat|null>(null);const[local,setLocal]=useState<CustomRat[]>([]);const[remote,setRemote]=useState<CustomRat[]>([]);const[loading,setLoading]=useState(false);const[message,setMessage]=useState('');const[session,setSession]=useState<Session|null>(null);const[email,setEmail]=useState('');const[password,setPassword]=useState('');const[loginLoading,setLoginLoading]=useState(false);
 useEffect(()=>{setLocal(loadLocal());const s=loadSession();setSession(s);if(s){freshSession().then(t=>{setSession(t);if(t)cloudProfiles().then(setRemote).catch(e=>setMessage(String(e)))})}},[]);
 async function generate(){setLoading(true);setMessage('');try{const res=await fetch('/api/generate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,borough,neighborhood})});if(!res.ok)throw Error(`Generator returned ${res.status}`);const p=await res.json() as CustomRat & {message?:string};setGenerated(p);setMessage(p.message||(p.source==='ai'?'Generated using the optional AI API.':'Generated from built-in templates. Add OPENAI_API_KEY to enable AI.'))}catch(e){setMessage(String(e))}finally{setLoading(false)}}
 async function save(){if(!generated)return;const next=[generated,...local];setLocal(next);saveLocal(next);onNew?.(generated);if(session){try{await cloudAdd(generated);setRemote(await cloudProfiles());setMessage('Saved to this browser and your cloud account.')}catch(e){setMessage(`Saved locally; cloud sync failed: ${String(e)}`)}}else setMessage('Saved to this browser. Sign in to sync new rats across devices.');}
 async function login(signup:boolean){setLoginLoading(true);setMessage('');try{const s=await auth(email,password,signup);setSession(s);if(s){setRemote(await cloudProfiles());setMessage('Welcome to the rat race. Your cloud account is connected.')}else setMessage('Check your inbox to confirm your email, then sign in.')}catch(e){setMessage(String(e))}finally{setLoginLoading(false)}}
 const showcase=session?remote:local;
 return <div className="studio"><div className="feed-header"><div><span className="eyebrow">SQUEEKDEN CAREER STUDIO</span><h2>Make a rat. Change its life.</h2></div></div><div className="card studio-card"><p>Create a fictional rodent professional. No actual individual animal is identified from city reports.</p><label>Rat&apos;s professional name<input maxLength={60} placeholder="e.g. Ratsby McCheese" value={name} onChange={e=>setName(e.target.value)}/></label><div className="studio-row"><label>Boston neighborhood<select value={borough} onChange={e=>{setBorough(e.target.value as Borough);setNeighborhood(e.target.value)}}>{boroughs.map(b=><option key={b}>{b}</option>)}</select></label><label>Neighborhood<input maxLength={65} value={neighborhood} onChange={e=>setNeighborhood(e.target.value)}/></label></div><button className="primary-btn" onClick={generate} disabled={loading}>{loading?'🐀 Networking furiously…':'✨ Generate rat career profile'}</button></div>{generated&&<div className="card result-card"><div className="result-top">🐀 <span>{generated.source==='ai'?'AI-GENERATED':'TEMPLATE-GENERATED'} · FICTIONAL</span></div><h2>{generated.name}</h2><strong>{generated.title}</strong><p>{generated.company} · {generated.neighborhood}, {generated.borough}</p><h3>About</h3><p>{generated.about}</p><h3>Latest career update</h3><p>{generated.post}</p><div className="skills">{generated.skills.map((s,i)=><span key={i}>{s}</span>)}</div><button className="primary-btn" onClick={save}>💾 Save this rat to my network</button></div>}
 <div className="card studio-card"><h3>🐁 Your rat network</h3><p>{session?`Cloud account: ${session.user.email||'signed in'}. New generated profiles are also saved locally.`:`Guest mode: ${local.length} rat(s) saved in this browser only.`}</p>{showcase.map((p,i)=><div className="saved-rat" key={i}><strong>🐀 {p.name}</strong><small>{p.title} · {p.borough}</small></div>)}{!showcase.length&&<p className="soft-note">No original rats saved yet. It&apos;s tough out there in the rat race.</p>}</div><div className="card studio-card"><h3>🔐 Real user accounts</h3>{cloudReady?<>{session?<><p>Signed in as {session.user.email||'a verified rat professional'}.</p><button className="secondary-btn" onClick={()=>{saveSession(null);setSession(null);setRemote([]);setMessage('Signed out of cloud account. Local guest rats remain on this browser.')}}>Sign out</button></>:<><p>Create an account or log in to sync your profiles to Supabase.</p><label>Email<input type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Password (at least 6 characters)<input type="password" autoComplete="current-password" minLength={6} value={password} onChange={e=>setPassword(e.target.value)}/></label><div className="button-row"><button className="primary-btn" disabled={loginLoading||!email||password.length<6} onClick={()=>login(false)}>Sign in</button><button className="secondary-btn" disabled={loginLoading||!email||password.length<6} onClick={()=>login(true)}>Sign up</button></div></>}</>:<p>Local guest mode is ready. To enable real accounts and cross-device database storage, set <code>NEXT_PUBLIC_SUPABASE_URL</code> and <code>NEXT_PUBLIC_SUPABASE_ANON_KEY</code>, then run the included SQL schema. See README.</p>}</div>{message&&<div className="card studio-card" role="status">{message}</div>}</div>
}
