export type Borough = 'Allston'|'Back Bay'|'Beacon Hill'|'Dorchester'|'East Boston'|'Jamaica Plain'|'Roxbury'|'South Boston';
export type Rat = {id:number;name:string;handle:string;title:string;company:string;borough:Borough;neighborhood:string;emoji:string;cover:string;experience:string;connections:string;skills:string[];about:string;post:string;likes:number;comments:number;posted:string};
export const boroughs:Borough[]=['Allston','Back Bay','Beacon Hill','Dorchester','East Boston','Jamaica Plain','Roxbury','South Boston'];
export const rats:Rat[]=[
{id:1,name:'Remy J. Rat III',handle:'remy-j-rat',title:'Senior Crumb Acquisition Specialist',company:'Dunkin (behind)',borough:'Allston',neighborhood:'Allston',emoji:'🐀',cover:'orange',experience:'8+ years',connections:'500+',skills:['Crumb Acquisition','Dumpster Strategy','Stakeholder Nibbling'],about:'Boston-based. Passionate about scaling food rescue through agile dumpster operations. Formerly Head of Bagels under Comm Ave.',post:'Thrilled to announce a new role at Dunkin (behind). Grateful for the crumbs, the mentors, and the growth mindset. 🧀 #OpenToWork #Allston',likes:1284,comments:93,posted:'2h'},
{id:2,name:'Cheddar Musk',handle:'cheddar-musk',title:'Founder & CEO, Subterranean Mobility',company:'SewerX',borough:'Jamaica Plain',neighborhood:'Jamaica Plain',emoji:'🐁',cover:'purple',experience:'12+ years',connections:'500+',skills:['Disruption','Tunnel Vision','Fundraising'],about:'Building the future of decentralized trash along the Orange Line. Opinions my own; dumpster belongs to everyone.',post:'We just raised $3 in pre-seed funding at a $40M valuation. No product. No customers. Tremendous tailwind in the garbage vertical.',likes:843,comments:176,posted:'4h'},
{id:3,name:'Ratrick Bateman',handle:'ratrick-bateman',title:'Vice President, Alternative Cheese Assets',company:'Goldman Snacks',borough:'Back Bay',neighborhood:'Back Bay',emoji:'🐀',cover:'blue',experience:'6+ years',connections:'500+',skills:['Arbitrage','PowerPoint','Cheese Derivatives'],about:'Focused on structured cheese products and managing diversified trash portfolios in volatile Boston markets.',post:'A lot of people ask how I maintain work-life balance. Simple: I don’t. I wake up at 4AM and eat drywall. Stay hungry.',likes:729,comments:44,posted:'6h'},
{id:4,name:'Mia Squeaks',handle:'mia-squeaks',title:'Chief Sustainability Officer',company:'Binance (the literal bins)',borough:'Dorchester',neighborhood:'Dorchester',emoji:'🐭',cover:'green',experience:'5+ years',connections:'342',skills:['Circular Economy','Composting','Trash Analytics'],about:'Transforming the way Boston thinks about waste. One discarded bagel at a time.',post:'In 2026, your “waste” is someone else’s runway. Proud to announce our Dorchester team recovered 47 bagels this quarter. #CircularEconomy',likes:512,comments:28,posted:'8h'},
{id:5,name:'Sir Squeaks-a-Lot',handle:'sir-squeaks',title:'Founder, Stealth Startup',company:'Undisclosed Basement',borough:'Roxbury',neighborhood:'Roxbury',emoji:'🐀',cover:'pink',experience:'3+ years',connections:'216',skills:['Networking','Stealth Mode','Product-Market Fit'],about:'Building in stealth. Can’t share much yet, but big things are coming to the under-the-floorboards space.',post:'Most founders chase product-market fit. I chase the person who dropped a pretzel on the Orange Line. We are not the same.',likes:392,comments:17,posted:'1d'},
{id:6,name:'Nibbles O’Malley',handle:'nibbles-omalley',title:'Independent Harbor Logistics Consultant',company:'Seaport Snack Infrastructure',borough:'South Boston',neighborhood:'South Boston',emoji:'🐁',cover:'teal',experience:'9+ years',connections:'187',skills:['Maritime Supply Chain','Bread Logistics','Resilience'],about:'Connecting waterfront snacks to underserved basement communities. Open to board seats and stale sandwich crust.',post:'Commuting is not a burden. It’s an opportunity to find dropped fries and form authentic connections. Sending this from Southie.',likes:281,comments:21,posted:'1d'},
{id:7,name:'Professor Squeakowitz',handle:'prof-squeakowitz',title:'Tenured Associate Professor of Crumbonomics',company:'MIT Department of Subterranean Studies',borough:'Beacon Hill',neighborhood:'Beacon Hill',emoji:'🐀',cover:'orange',experience:'11+ years',connections:'500+',skills:['Research','Grant Writing','Cheese Economics'],about:'Published 19 peer-reviewed papers on discarded pizza slice elasticity. The data are squeaking for themselves.',post:'Thrilled to share our NSF grant: $1.6M to study why students drop fries outside the T. All findings open access. #AcademicTwitter',likes:1092,comments:82,posted:'1d'},
{id:8,name:'Lobster McNibbles',handle:'lobster-mcnibbles',title:'Director of Airport Crumb Operations',company:'Logan Terminal Squeak',borough:'East Boston',neighborhood:'East Boston',emoji:'🐁',cover:'blue',experience:'4+ years',connections:'433',skills:['Aviation Snacks','Cargo','Airport Networking'],about:'I turn delayed flights into scalable pretzel opportunities.',post:'Delighted to announce strategic expansion into Terminal B. A huge thank you to everyone who left a bagel unattended.',likes:611,comments:27,posted:'2d'}
];
export const demoCounts:Record<Borough,number>={Allston:55,'Back Bay':72,'Beacon Hill':38,Dorchester:108,'East Boston':43,'Jamaica Plain':64,Roxbury:84,'South Boston':95};
